### ISSUE TITLE
Null pointer dereference in hsql::printExpression

### ISSUE THREAD

**Issue by hac425xxx** [hyrise/sql-parser#132]
Version : sql-parser-1.5

The cmdline 
```
./example "SELECT 'as' FROM a TYPE WHERE a ( 0+0+0 )"
```

crash context in gdb

```
Reading symbols from ./example...(no debugging symbols found)...done.
pwndbg: loaded 181 commands. Type pwndbg [filter] for a list.
pwndbg: created $rebase, $ida gdb functions (can be used with print/break)
pwndbg> r
Starting program: /home/xxx/workplace/dbg/sql-parser-1.5/example/example SELECT\ \'as\'\ FROM\ a\ TYPE\ WHERE\ a\ \(\ 0+0+0\ \)
Parsed successfully!
Number of statements: 1
SelectStatement
	Fields:
		as
	Sources:
		a
			Alias
				TYPE
	Search Conditions:
		a

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7bb42aa in hsql::printExpression (expr=0x6035b0, numIndent=2) at src/sqlhelper.cpp:106
106	      inprint(expr->expr->name, numIndent + 1);
LEGEND: STACK | HEAP | CODE | DATA | RWX | RODATA
───────────────────────────────────────────────────────────────────────────────[ REGISTERS ]────────────────────────────────────────────────────────────────────────────────
 RAX  0x0
 RBX  0x0
 RCX  0x0
 RDX  0x3
 RDI  0x0
 RSI  0xffffffff
 R8   0x0
 R9   0x603060 ◂— 0x0
 R10  0x7ffff766e6a0 (_IO_file_jumps) ◂— 0x0
 R11  0x246
 R12  0x400cb0 (_start) ◂— xor    ebp, ebp
 R13  0x7fffffffe0e0 ◂— 0x2
 R14  0x0
 R15  0x0
 RBP  0x7fffffffdf30 —▸ 0x7fffffffdf90 —▸ 0x7fffffffdfb0 —▸ 0x7fffffffe000 ◂— 0x0
 RSP  0x7fffffffdf10 —▸ 0x603078 ◂— 0x9000909 /* '\t\t' */
 RIP  0x7ffff7bb42aa ◂— mov    rax, qword ptr [rax + 0x28]
─────────────────────────────────────────────────────────────────────────────────[ DISASM ]─────────────────────────────────────────────────────────────────────────────────
 ► 0x7ffff7bb42aa    mov    rax, qword ptr [rax + 0x28]
   0x7ffff7bb42ae    mov    rsi, rdx
   0x7ffff7bb42b1    mov    rdi, rax
   0x7ffff7bb42b4    call   0x7ffff7bab2d0
 
   0x7ffff7bb42b9    jmp    0x7ffff7bb42f8
 
   0x7ffff7bb42bb    mov    rdx, qword ptr [rbp - 0x10]
   0x7ffff7bb42bf    mov    rax, qword ptr [rbp - 8]
   0x7ffff7bb42c3    mov    rsi, rdx
   0x7ffff7bb42c6    mov    rdi, rax
   0x7ffff7bb42c9    call   0x7ffff7babca0
 
   0x7ffff7bb42ce    jmp    0x7ffff7bb42f8
─────────────────────────────────────────────────────────────────────────────[ SOURCE (CODE) ]──────────────────────────────────────────────────────────────────────────────
In file: /home/xxx/workplace/dbg/sql-parser-1.5/src/sqlhelper.cpp
   101     case kExprLiteralString:
   102       inprint(expr->name, numIndent);
   103       break;
   104     case kExprFunctionRef:
   105       inprint(expr->name, numIndent);
 ► 106       inprint(expr->expr->name, numIndent + 1);
   107       break;
   108     case kExprOperator:
   109       printOperatorExpression(expr, numIndent);
   110       break;
   111     default:
─────────────────────────────────────────────────────────────────────────────────[ STACK ]──────────────────────────────────────────────────────────────────────────────────
00:0000│ rsp  0x7fffffffdf10 —▸ 0x603078 ◂— 0x9000909 /* '\t\t' */
01:0008│      0x7fffffffdf18 ◂— 0x0
02:0010│      0x7fffffffdf20 ◂— 0x2
03:0018│      0x7fffffffdf28 —▸ 0x6035b0 ◂— 0x6
04:0020│ rbp  0x7fffffffdf30 —▸ 0x7fffffffdf90 —▸ 0x7fffffffdfb0 —▸ 0x7fffffffe000 ◂— 0x0
05:0028│      0x7fffffffdf38 —▸ 0x7ffff7bb4460 ◂— mov    rax, qword ptr [rbp - 0x48]
06:0030│      0x7fffffffdf40 ◂— 0x0
07:0038│      0x7fffffffdf48 —▸ 0x603620 —▸ 0x7ffff7dd7990 —▸ 0x7ffff7bafb00 (hsql::SelectStatement::~SelectStatement()) ◂— push   rbp
───────────────────────────────────────────────────────────────────────────────[ BACKTRACE ]────────────────────────────────────────────────────────────────────────────────
 ► f 0     7ffff7bb42aa
   f 1     7ffff7bb4460
   f 2     7ffff7bb4846
   f 3           400e81 main+228
   f 4     7ffff72cef45 __libc_start_main+245
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Program received signal SIGSEGV (fault address 0x28)
pwndbg> bt
#0  0x00007ffff7bb42aa in hsql::printExpression (expr=0x6035b0, numIndent=2) at src/sqlhelper.cpp:106
#1  0x00007ffff7bb4460 in hsql::printSelectStatementInfo (stmt=0x603620, numIndent=0) at src/sqlhelper.cpp:131
#2  0x00007ffff7bb4846 in hsql::printStatementInfo (stmt=0x603620) at src/sqlhelper.cpp:192
#3  0x0000000000400e81 in main ()
#4  0x00007ffff72cef45 in __libc_start_main (main=0x400d9d <main>, argc=2, argv=0x7fffffffe0e8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffe0d8) at libc-start.c:287
#5  0x0000000000400cd9 in _start ()

```

**Comment by mrks** [comment]
Thanks for letting us know. The bug has been fixed on master for a while now.

I didn't realize that there were tagged releases for the sql-parser - those were added before I took over its maintenance. Since we don't have any type of release management, I disabled the releases.
